# Generated by Django 3.1.4 on 2021-01-08 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=1024, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.language')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('image', models.CharField(max_length=1024)),
                ('audio', models.CharField(max_length=1024)),
                ('desc', models.CharField(max_length=999999)),
                ('date', models.DateTimeField()),
                ('movie_album_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.moviealbum')),
            ],
        ),
    ]
