# Generated by Django 3.1.4 on 2021-01-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='date',
            field=models.DateField(),
        ),
    ]
